# Generated by Django 2.2 on 2021-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gossip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
